---
apiVersion: v1
kind: Namespace
metadata:
  name: reboot-coordinator

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-updater-agent
  namespace: reboot-coordinator
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        app: node-updater-agent
    spec:
      serviceAccount: node-updater-agent
      containers:
        - name: updater-agent
          image: quay.io/mad01/k8s-node-updater:fe86470f310d80fc40422f2cd25c7961d4a0b77d
          securityContext:
            privileged: true
          command:
            - "./k8s-node-updater"
          args:
            - "agent"
            - "-node.name=$(NODE_NAME)"
            - "-update.interval=60s"
          volumeMounts:
            - mountPath: /var/run/dbus
              name: var-run-dbus
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: var-run-dbus
          hostPath:
            path: /var/run/dbus


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-updater-agent
  namespace: reboot-coordinator

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: node-updater-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: node-updater-agent
    namespace: reboot-coordinator
